replicaCount: 1

image:
  repository: redis
  pullPolicy: IfNotPresent
  tag: "7.0.0-alpine" # Using a lightweight Redis image

service:
  type: ClusterIP
  port: 6379 # Default Redis port

redisPort: 6379 # Exposing Redis port for probes and other applications
