apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "app-b.fullname" . }}
  labels:
    {{- include "app-b.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "app-b.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "app-b.labels" . | nindent 8 }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "redis:7.2.4-alpine"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command: ["redis-cli", "-h", "app-a-redis", "-p", "6379", "ping"]
          ports:
            - name: http
              containerPort: {{ .Values.service.port }}
              protocol: TCP
